version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
      # - 9229:9229
    volumes:
      - .:/app
    # command: npm run start:debug
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mysql/mysql-server:8.0.23
    # platform: linux/arm64
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306